### ISSUE TITLE
关于在NextQA上的运行代码

### ISSUE THREAD

**Issue by LemonQC** [zhangxi1997/VQACL#9]

**Comment by tobocca** [comment]
您好，请问您的Question_type.py文件里的29行 with open('datasets/QuesId_task_map.json') as fp:中的QuesId_task_map.json文件在哪里获得的，还有32行的ImgId_cate_map.json文件，不胜感谢，期待回复。

**Comment by zhangxi1997** [comment]
The rough code for NExT-QA has been uploaded...
